[package]
name = "lerning"
version = "0.1.0"
authors = ["chunlinwang <chunlinwang1983@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
futures = "0.3.6"
argonautica = "0.2.0"

